volumes:
    wordpress:
        name: wordpress-vol
        driver: local
        driver_opts:
          type: none
          device: /home/bsyvasal/data/wordpress
          o: bind
    mariadb:
        name: mariadb-vol
        driver: local
        driver_opts:
          type: none
          device: /home/bsyvasal/data/mariadb
          o: bind

networks:
    inception:
        name: syvanet
        driver: bridge

services:
    ngnix:
        container_name: ngnix-cont
        build: ./requirements/nginx
        image: ngnix
        ports:
            - "443:443"
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/html
        env_file:
            - .env
        networks:
            - inception
        restart: always

    wordpress:
        container_name: wordpress-cont
        build: ./requirements/wordpress
        image: wordpress
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/html
        env_file:
            - .env
        networks:
            - inception
        restart: always

    mariadb:
        container_name: mariadb-cont
        build: ./requirements/mariadb
        image: mariadb
        volumes:
            - mariadb:/var/lib/mysql
        env_file: .env
        networks: 
            - inception
        restart: always